name: Frontend Build CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: docker build -t schedule:latest .
      - run: docker run -d -p 80:80 schedule:latest